language: java
jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk8
dist: trusty
sudo: false

script: mvn test

after_success:
  - mvn clean jacoco:prepare-agent install jacoco:report coveralls:report

notifications:
  webhooks: https://coveralls.io/webhook

cache:
  directories:
    - $HOME/.m2