language: java

dist: trusty


jobs:
  include:
    - os: linux
      dist: trusty
      jdk:
        - oraclejdk8
        - oraclejdk9
        - oraclejdk11
        - openjdk8
    - os: linux
      dist: bionic
      jdk:
        - oraclejdk11
        - openjdk8

sudo: false

script: mvn test

after_success:
  - mvn clean jacoco:prepare-agent install jacoco:report coveralls:report

cache:
  directories:
    - $HOME/.m2